In [3]:
import numpy as np

In [12]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [6]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


**(1,7) dersek diziye 1,2,3,4,5,6 ekler ama y yi eklemez!!!**

In [7]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


**50 ve 101 arasında 6 tane random integer sayı oluşturmak için;**

In [8]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[50 92 85 99 63 73]


**0 ve 1 arasında float 6 tane sayı oluşturmak için;**

In [9]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.13368012 0.31497928 0.53947106 0.44136157 0.68904532 0.93091707]


**yukarda oluşturduğumuz float 6 tane sayıyı 2 ile topladık ve 2 ve 3 arasında random 6 sayı elde ettik**

In [10]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.13368012 2.31497928 2.53947106 2.44136157 2.68904532 2.93091707]


**50 ve 100 arasında oluşturulan random sayıları 3 ile çarparak 150 ve 300 arasında random sayılar elde ettik**

In [11]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[150 276 255 297 189 219]


**TASK1 Create a Linear Dataset**



6 ve 20 arasında sayılardan oluşan dizi(20 dahil);

In [21]:
feature = np.arange(6,21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


label=3*feature+4

In [22]:
label = 3*feature+4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


**TASK2 Add Some Noise to the Dataset**

In [23]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[-1.58286416e+00  1.36259851e-01  1.70501657e+00  1.08442078e+00
  1.53745460e+00 -9.68305577e-02  4.05079302e-01  6.01439260e-01
  3.31316668e-04 -2.31962566e-01  1.49538339e+00  5.95023206e-02
  5.77465314e-02  5.46588797e-01  3.47828996e-01]
[20.41713584 25.13625985 29.70501657 32.08442078 35.5374546  36.90316944
 40.4050793  43.60143926 46.00033132 48.76803743 53.49538339 55.05950232
 58.05774653 61.5465888  64.347829  ]
